### ISSUE TITLE
Compilation on Windows?

### ISSUE THREAD

**Issue by xuanjianwu** [fairf4x/VIZ#3]
Dear fairf4x, I try to build VIZ on windows with Qt, but I find it difficult to import igraph in VIZ, I used to build igraph on VS2013 and export a XXX.lib file, but it can not be used in VIZ directly with QT. Please could you help me?

Best wishs

**Comment by fairf4x** [comment]
Currently I do not have access to any windows machine to test windows build.
You can try to download the original [installation package for windows](http://ktiml.mff.cuni.cz/~bartak/clp/downloads/VIZ_Windows.msi) and try to reverse engineer it.
